name: Production Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Setup
        id: setup
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Build and Deploy
        id: build-and-deploy
        run: flyctl deploy --app headless-three-prod
